include "/etc/bind/esclavo.key";

masters maestro-dns {
    192.168.50.3 key "esclavo-key";
};

zone "empresa.local" {
    type slave;
    masters { maestro-dns; };
    file "/var/cache/bind/db.empresa.local";
};

zone "50.168.192.in-addr.arpa" {
    type slave;
    masters { maestro-dns; };
    file "/var/cache/bind/db.50.168.192";
};
